export { default as Header } from "./header/Header";
export { default as Footer } from "./footer/Footer";
export { default as Hero } from "./hero/Hero";
export { default as About } from "./about/About";
export { default as Skills } from "./skills/Skills";
export { default as Projects } from "./projects/Projects";
export { default as ContactForm } from "./contactform/ContactForm";
export { default as ProjectCard } from "./projectcard/ProjectCard";
export { default as Socials } from "./socials/Socials";
